- lib/yform/value/choice_html.php
- ytemplates/bootstrap/value.choice_html.check.tpl.php
- ytemplates/bootstrap/value.choice_html.select.tpl.php
https://github.com/yakamara/redaxo_yform/pull/896
closes #8
> choice with html ouput

- README.md
- lib/yform/value/datetime_local.php
https://github.com/yakamara/redaxo_yform/pull/1239
> neues datetime-Field

- lib/yform/value/media_preview.php
- package.yml
> Media preview

- lib/yform/validate/iban.php
> initial iban

- lib/yform/action/session.php
- lib/yform/action/to_session.php
Hatte ich mal vor Jahrzehnten aus dem Forum, finde ich sehr nützlich.
> Session Action

- lib/yform/value/form_url.php
> add `form_url` value

- lib/yform/value/be_user_select.php
> value `be_user_select` for `rex_user`-Table

- install.php
Behebt Woops wg. setOutputStyle (Slack-Meldung von @ingoschaefer)
> Formatter geändert

- lang/de_de.lang
- lib/yform/value/datestamp_offset.php
> Neues Feld `datestamp_offset`

- fragments/choice_status_select.php
> Status-Select-Feld optisch anpassen

- lib/yform_api_choice_status.php
- package.yml
> `choice_status` auf Überprüfung von $value verzichten

- lib/yform/value/select.php
https://github.com/alexplusde/neues/issues/16
> fix `explode()` Warning

- boot.php
- fragments/choice_status_select.php
- install.php
- lib/yform/action/attach/attach.php
- lib/yform/action/to_session.php
- lib/yform/value/be_user_select.php
- lib/yform/value/choice_html.php
- lib/yform/value/choice_status.php
- lib/yform/value/datestamp_offset.php
- lib/yform/value/datetime_local.php
- lib/yform/value/domain.php
- lib/yform/value/form_url.php
- lib/yform/value/media_preview.php
- lib/yform/value/privacy_policy.php
- lib/yform/value/radio.php
- lib/yform/value/radio_sql.php
- lib/yform/value/select.php
- lib/yform/value/select_sql.php
- lib/yform/value/submit_once.php
- lib/yform/value/tabs.php
- lib/yform_api_choice_status.php
- pages/yform_field.settings.php
- update.php
- ytemplates/bootstrap/value.checkbox-privacy_policy.tpl.php
- ytemplates/bootstrap/value.choice_html.check.tpl.php
- ytemplates/bootstrap/value.choice_html.select.tpl.php
- ytemplates/bootstrap/value.radio.tpl.php
- ytemplates/bootstrap/value.select.tpl.php
- ytemplates/bootstrap/value.submit_once.tpl.php
- ytemplates/bootstrap/value.tabs.tpl.php
> Workaround bei fehlender Spalte 'group_by'

- ytemplates/bootstrap/value.checkbox-privacy_policy.tpl.php
> DSGVO-Checkbox barrierefrei umsetzen

- README.md
- ytemplates/bootstrap/value.checkbox-privacy_policy.tpl.php
Bitte Melden wenn was im Github-Prozess klemmt. Ich hab das als Textcase genommen in Sachen "VSCode und Github" und nun taucht hier drin ein längst gemachter PR #64 von Dir in einer Deiner Branches mit auf. Warum auch immer GitHub den hier präsentiert ....
> Tab-Value in die Readme aufgenommen

- boot.php
- install.php
- lib/yform/action/to_session.php
- lib/yform/validate/compromised.php
- lib/yform/value/choice_status.php
- lib/yform/value/domain.php
- pages/yform_field.settings.php
> fix syntax error

- fragments/choice_status_select.php
- fragments/history_push.php
- lib/yform/action/history_push.php
Action, die erschwert, dass Formulare mehrfach abgesendet werden, indem der History-State verändert wird.
> Basic Action `history_push`

- boot.php
- install.php
- lib/yform/action/attach/attach_signature.php
- lib/yform/action/conversion_push.php
- lib/yform_field.php
Bereit für Review.
Optionale Verbesserung vor PR-Annahme: Statt Feldnamen angeben zu müssen, automatisch das Signaturfeld aus den Feldern ermitteln.
> Action: Attach Signature

- lib/yform/value/choice_html.php
- lib/yform/value/custom_link.php
- ytemplates/bootstrap/value.custom_link.tpl.php
closes #84
Danke @akuehnis, deine Infos zur Korrektur waren korrekt. Danke @iriswerner fürs Testen.
> fix rex_var_custom_link

- lang/de_de.lang
- lib/yform/value/radio.php
- lib/yform/value/radio_sql.php
- lib/yform/value/select.php
- lib/yform/value/select_sql.php
> Deprecate Fields in 2.x - Radio/Select-Felder aus YForm 3 für YForm Field 3 entfernen

- ytemplates/bootstrap/value.submit_once.tpl.php
> nonce zu submit_once hinzufügen

- install.php
- install/yform_choice_patch.php
> Patch YForm Choice like it's 2001 (PHPBB-Style)

- install.php
- install/yform/uuid.php
- install/yform_choice_patch.php
- install/yform_field_list_patch.php
- install/yform_uuid_patch.php
- lib/yform/value/domain.php
Weil https://github.com/yakamara/yform/commit/df79eff090ad0460c655c2f852b17e6aec53987a immer noch nicht im Installer ist.
> Ermöglicht, Datensätze mit UUID zu klonen
